server:
  port: 80
  forward-headers-strategy: native
  undertow:
    threads:
      worker: 16
      io: 4
spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1100MB
  datasource:
    hikari:
      jdbc-url: jdbc:h2:retry:${record.work-path}/db
    username: sa
    password: 123456
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          #为spring data jpa saveAll方法提供批量插入操作 此处可以随时更改大小 建议500哦
          batch_size: 1000
          batch_versioned_data: true
          order_inserts: true
    database-platform: org.hibernate.dialect.H2Dialect
  thymeleaf:
    cache: false
  task:
    scheduling:
      pool:
        size: 10
#  h2:
#    console:
#      enabled: true

record:
  userName:
  password:
  work-path: /bilirecord
  wx-push-token: AT_oboGsjlaGphljfVS9TtC7JfuBB0xPJrn

bili:
  app-key: 4409e2ce8ffd12b8
  app-secret: 59b43e04ad6965f34319062b478f83dd

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: WARN
    top.sshh.bililiverecoder: DEBUG
  file:
    path: ${record.work-path}/log/
  logback:
    rollingpolicy:
      max-file-size: 50MB
